local:
  dialect: postgres
  datasource: host=localhost dbname=go-sample-api_local user=postgres password=password port=5438 sslmode=disable
  dir: infrastructure/db/migrations
  table: gorp_migrations

test:
  dialect: postgres
  datasource: host=localhost dbname=test user=test password=test port=5439 sslmode=disable
  dir: infrastructure/db/migrations
  table: gorp_migrations

ci:
  dialect: postgres
  datasource: host=localhost dbname=test user=test password=test port=5439 sslmode=disable
  dir: infrastructure/db/migrations
  table: gorp_migrations
